import React from 'react';
import Head from 'next/head';
import Appbar from '@/components/shared/AppBar/Appbar';
export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Shift-ERP</title>
        <meta name='description' content='Generated by Shift-ERP' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {/* <Appbar /> */}
        <h1>Next Template</h1>
      </main>
    </React.Fragment>
  )
}
